// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJSDIEtFbPszhet06L1tnsd9jyWFV9LRQ',
    appId: '1:167036504587:web:41fb0bc335fbaccd7bd50e',
    messagingSenderId: '167036504587',
    projectId: 'car-parking-system-feb0d',
    authDomain: 'car-parking-system-feb0d.firebaseapp.com',
    storageBucket: 'car-parking-system-feb0d.appspot.com',
    measurementId: 'G-W1JFL527R9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcZu4rqyDR9AFleNhU9XxwvW0gKBv1Xko',
    appId: '1:167036504587:android:1e137360dadf2f117bd50e',
    messagingSenderId: '167036504587',
    projectId: 'car-parking-system-feb0d',
    storageBucket: 'car-parking-system-feb0d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsCRZeYiPbhJAGBTuzxH_zPOQLX1c27wg',
    appId: '1:167036504587:ios:562b2c89260dc06f7bd50e',
    messagingSenderId: '167036504587',
    projectId: 'car-parking-system-feb0d',
    storageBucket: 'car-parking-system-feb0d.appspot.com',
    iosBundleId: 'com.example.carParkingSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBsCRZeYiPbhJAGBTuzxH_zPOQLX1c27wg',
    appId: '1:167036504587:ios:562b2c89260dc06f7bd50e',
    messagingSenderId: '167036504587',
    projectId: 'car-parking-system-feb0d',
    storageBucket: 'car-parking-system-feb0d.appspot.com',
    iosBundleId: 'com.example.carParkingSystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDJSDIEtFbPszhet06L1tnsd9jyWFV9LRQ',
    appId: '1:167036504587:web:fb4af37c57ed71347bd50e',
    messagingSenderId: '167036504587',
    projectId: 'car-parking-system-feb0d',
    authDomain: 'car-parking-system-feb0d.firebaseapp.com',
    storageBucket: 'car-parking-system-feb0d.appspot.com',
    measurementId: 'G-J8WLQBX188',
  );
}
